/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "n5.1.3-19-gec2ec8e5fc"
#endif /* AVUTIL_FFVERSION_H */
